{% set name = "the_silver_searcher" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ggreer/the_silver_searcher/archive/{{ version }}.tar.gz
  sha256: cb416a0da7fe354a009c482ae709692ed567f8e7d2dad4d242e726dd7ca202f0

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - make
    - cram
    - pkg-config 
  host:
    - pcre
    - xz
    - zlib
  run:
    - {{ pin_compatible('pcre') }}
    - xz
    - zlib

test:
  commands:
    - ag --help

about:
  home: https://geoff.greer.fm/ag
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A code searching tool similar to ack, with a focus on speed.'
  dev_url: https://github.com/ggreer/the_silver_searcher

extra:
  recipe-maintainers:
    - nehaljwani
    - dougalsutherland
