appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jxKGnPvQxEejmJHpZp1e1GfYdfqTOcJ1V3BppRZsyJ8cpSd3KrK1JOzOormpA2pjvtmDZgnreeaajVUXNWx81li1EC2exnwvTQabtJMImJo7UD9/J8Zg0qjbPsrmYRdeiSnHOP+2evQij2dNgL13e6Mhe0kjXgV0ZLlxS6ukRh6jWYsdl2PNApv0JbHJCvoP8Rs/bqq6oL4/Dc4F0Iv9Lzi6MDGrL/sOMxI4W0u4Zer63w6EmtbnRu7CEwQGmlsEH+9cAIukTGoBdVAkMp3Gtt6isAcwz8ui9gbWTNWJscPOj5BOhbeXE74j0vU6QjxwveFfQOX/xW72CbpgmygCOpzfJ/yV3nXcrSSYanhx1cwLrpLwZpmUDY0OlXNjdBV0w2MDHtCOT5KhQvXPQFk/k6ZJw3EoVv+rK8N6M/wpIxI+L/IuS3bMrjS7TEuJYS+Uru6OhP8OV/90y9YMWuQKnGr/LUBEGiT+EY7F9Lb5zncWWSypGYSPoPoJOeVy1ioLERaC8gyRdmFIgX/5Y900eQLBMaQ43Gkn6Zy/GLOc2Yz8570AAPd8FJMXTLyhE2u10MDtA/cCFoDA+OXyA071BQGgVzr4hqcnfZwuCUhNub7J6lxG701tSEunpcYO1sRLRn6U/mtzZMDCcQ8gpoDv9Y389HXb+CvYKOQ56ZkSc+0=}
